<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="160638" started-at="2019-01-28T03:50:53Z" finished-at="2019-01-28T03:53:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="160638" started-at="2019-01-28T03:50:53Z" finished-at="2019-01-28T03:53:34Z">
      <class name="testexecution.Execute">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testexecution.Execute@3b938003]" name="beforeTest" is-config="true" duration-ms="13340" started-at="2019-01-28T09:20:53Z" finished-at="2019-01-28T09:21:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="bookSinglePassenger(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testexecution.Execute@3b938003]" name="bookSinglePassenger" duration-ms="26519" started-at="2019-01-28T09:21:07Z" data-provider="SingleData" finished-at="2019-01-28T09:21:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[a@b.c]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ninad ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Katekae]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[MR]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[7.894567894E9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid Email ID]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid Email ID
	at org.testng.Assert.fail(Assert.java:93)
	at utils.Util.verifyOnInvisibilty(Util.java:130)
	at POM.BookSinglePassenger.bookSingle(BookSinglePassenger.java:35)
	at testexecution.Execute.bookSinglePassenger(Execute.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookSinglePassenger -->
        <test-method status="FAIL" signature="bookSinglePassenger(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testexecution.Execute@3b938003]" name="bookSinglePassenger" duration-ms="28199" started-at="2019-01-28T09:21:33Z" data-provider="SingleData" finished-at="2019-01-28T09:22:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[a@b.co]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[-]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[1.536784595E9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error on FirstName]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error on FirstName
	at org.testng.Assert.fail(Assert.java:93)
	at utils.Util.verifyOnEnability(Util.java:101)
	at POM.BookSinglePassenger.bookSingle(BookSinglePassenger.java:47)
	at testexecution.Execute.bookSinglePassenger(Execute.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookSinglePassenger -->
        <test-method status="FAIL" signature="bookSinglePassenger(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testexecution.Execute@3b938003]" name="bookSinglePassenger" duration-ms="54426" started-at="2019-01-28T09:22:02Z" data-provider="SingleData" finished-at="2019-01-28T09:22:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[a@b.co]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Fibin]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Cherian]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[MR]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[8456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid Mobile Number]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid Mobile Number
	at org.testng.Assert.fail(Assert.java:93)
	at utils.Util.verifyOnInvisibilty(Util.java:130)
	at POM.BookSinglePassenger.bookSingle(BookSinglePassenger.java:94)
	at testexecution.Execute.bookSinglePassenger(Execute.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookSinglePassenger -->
        <test-method status="PASS" signature="bookSinglePassenger(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testexecution.Execute@3b938003]" name="bookSinglePassenger" duration-ms="37961" started-at="2019-01-28T09:22:56Z" data-provider="SingleData" finished-at="2019-01-28T09:23:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[a@b.co]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Fibin]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Cherian]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[MR]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[8.450963111E9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookSinglePassenger -->
      </class> <!-- testexecution.Execute -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
